openapi: "3.0.0"
info:
    version: "1.0"
    title: "Mineral Contest Serverless API"
tags:
    - name: auth
paths:
    /auth/login:
        post:
            tags:
                - auth
            description: Login using username and password
            responses:
                200:
                    description: OK
            x-amazon-apigateway-integration:
                uri: "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${login_lambda_arn}/invocations"
                httpMethod: "POST"
                passthroughBehavior: "when_no_match"
                timeoutInMillis: 10000
                type: "aws"
            x-amazon-apigateway-auth:
                type: "NONE"
            x-amazon-apigateway-api-key-source: "HEADER"





    /auth/me:
        get:
            tags:
                - auth
            description: Register
            responses:
                200:
                    description: ok
            x-amazon-apigateway-integration:
                uri: "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${me_lambda_arn}/invocations"
                httpMethod: "POST"
                passthroughBehavior: "when_no_match"
                timeoutInMillis: 10000
                type: "aws"
            x-amazon-apigateway-auth:
                type: "${cognito_authorizer_name}"
            x-amazon-apigateway-api-key-source: "HEADER"

    /auth/register:
        post:
            tags:
                - auth
            description: Register
            responses:
                200:
                    description: ok
            x-amazon-apigateway-integration:
                uri: "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${register_lambda_arn}/invocations"
                httpMethod: "POST"
                passthroughBehavior: "when_no_match"
                timeoutInMillis: 10000
                type: "aws"
            x-amazon-apigateway-auth:
                type: "NONE"
            x-amazon-apigateway-api-key-source: "HEADER"
            