swagger: "2.0"
info:
  version: "1.0"
  title: "Mineral Contest Serverless API" 
tags:
  - name: auth
paths:
  /auth/login:
    post:
      tags:
        - auth
      description: Login using username and password
      responses:
        200:
          description: OK
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${login_lambda_arn}/invocations"
        httpMethod: "POST"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 10000
        type: "aws_proxy"
      x-amazon-apigateway-auth:
        type: "NONE"
      x-amazon-apigateway-api-key-source: "HEADER"



  /auth/register:
    post:
      tags:
        - auth
      description: Register
      responses:
        200:
          description: ok

  /maps/:
    get:
      description: List all the available maps
      responses:
        200:
          description: Returns the list of available maps.
          schema:
            type: array
            items:
              type: object
              properties:
                map-name:
                  type: string
                  example: Egypt
                description:
                  type: string
                  example: This world is a copy of Egypt.
                author:
                  type: string
                  example: Pgjgj
                download-url:
                  type: string
                  example: https://download-url.com/egypt.zip
                map-images:
                  type: array
                  items:
                    type: string
                    example: [https://download-url.com/egypt/bg1.jpg, https://download-url.com/egypt/bg2.jpg]
    post:
      description: Add a new map
      parameters:
        - name: world_name
          in: header
          type: string
          description: The name of the world to upload
          required: true
        - name: world_description
          in: header
          type: string
          description: The description of the world to upload
          required: true
        - name: world_images
          in: header
          type: string
          format: binary
          description: Images that illustrate the map, at least one image is required
          required: true
        - name: world_file
          in: header
          type: string
          format: binary
          description: ZIP archive of the created map
          required: true
        - name: user_key
          in: header
          type: string
          description: User API key to perform the action
          required: true
      responses:
        200:
          description: Returns the created map 
          schema:
            type: object
            properties:
              map-name:
                type: string
                example: Egypt
              description:
                type: string
                example: This world is a copy of Egypt.
              author:
                type: string
                example: Pgjgj
              download-url:
                type: string
                example: https://download-url.com/egypt.zip
              map-images:
                type: array
                items:
                  type: string
                  example: [https://download-url.com/egypt/bg1.jpg, https://download-url.com/egypt/bg2.jpg]
    put:
      description: Update the given map
      parameters:
        - name: map_id
          in: header
          type: string
          required: true
        - name: user_key
          in: header
          type: string
          description: User API key to perform the action
          required: true
        - name: world_name
          in: header
          type: string
          description: The name of the world to upload
          required: false
        - name: world_description
          in: header
          type: string
          description: The description of the world to upload
          required: false
        - name: world_file
          in: header
          type: string
          format: binary
          description: ZIP archive of the created map
          required: false
        - name: world_images
          in: header
          type: string
          format: binary
          description: Images that illustrate the map, at least one image is required
          required: false
      responses:
        200:
          description: Returns the updated map 
          schema:
            type: object
            properties:
              map-name:
                type: string
                example: Egypt
              description:
                type: string
                example: This world is a copy of Egypt.
              author:
                type: string
                example: Pgjgj
              download-url:
                type: string
                example: https://download-url.com/egypt.zip
              map-images:
                type: array
                items:
                  type: string
                  example: [https://download-url.com/egypt/bg1.jpg, https://download-url.com/egypt/bg2.jpg]

        

        

               


