name: Push to CodeCommit

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Configure AWS credentials
      #uses: aws-actions/configure-aws-credentials@v1
      #with:
      #  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #  aws-region: ${{ secrets.AWS_CODEDEPLOY_REGION }}

      - name: Push to CodeCommit
        shell: bash
        run: |
          mkdir .ssh && cd .ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa && chmod 600 id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > config && chmod 600 config
          git remote add codecommit https://git-codecommit.${{ secrets.AWS_CODEDEPLOY_REGION }}.amazonaws.com/v1/repos/${{ secrets.AWS_CODEDEPLOY_REPO_NAME }}
          git push codecommit master --force
